fullstack_ror/todolists_m3/config/routes.rb
Rails.application.routes.draw do
  

  resources :todo_items
  

end

fullstack_ror/todolists_m3/app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  def self.completed_count
    TodoItem.where(completed: true).count
  end
end

fullstack_ror/todolists_m3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

fullstack_ror/todolists_m3/app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: %i[show edit update destroy]
  
  def index
    @todo_items = TodoItem.all
    @number_of_completed_todos = TodoItem.completed_count
  end

  def show; end

  def new
    @todo_item = TodoItem.new
  end

  def edit; end

  def create
    @todo_item = TodoItem.new(todo_item_params)
    
    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to todo_items_path, notice: 'Todo item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
    end
  end
  
  private

  def set_todo_item
    @todo_item = TodoItem.find(params[:id])
  end

  def todo_item_params
    params.require(:todo_item).permit(:due_date, :title, :completed, :description)
  end
end

fullstack_ror/todolists_m3/app/helpers/application_helper.rb
module ApplicationHelper
end

fullstack_ror/todolists_m3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodolistsActionpack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

fullstack_ror/todolists_m3/app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
    <% if @todo_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

          <ul>
            <% @todo_item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :due_date %>
      <%= f.date_select :due_date %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, size: '20x3' %>
    </div>

    <% if f.object.persisted? %>
        <div class="field">
          <%= f.label :completed %>
          <%= f.text_field :completed %>
        </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

fullstack_ror/todolists_m3/app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form', todo_item: @todo_item %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

fullstack_ror/todolists_m3/app/views/todo_items/index.html.erb
<h1>Listing Todo Items</h1>
<p>Number of Completed Todos: <%= @number_of_completed_todos %></p>
<p id="notice"><%= notice %></p>
<table>
  <% @todo_items.each do |todo_item| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= todo_item.title %>
          <%= link_to 'Show', todo_item %>
          <%= link_to 'Destroy', todo_item, method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Todo item', new_todo_item_path %>

fullstack_ror/todolists_m3/app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form', product: @todo_item %>

<%= link_to 'Back', todo_items_path %>

fullstack_ror/todolists_m3/app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>